name = "TestRepo"
uuid = "90af04c2-c497-4a6d-ab87-4f06308bc264"
authors = ["Asad Hussain"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
